services:
  - type: web
    name: starrynight-backend
    runtime: node
    buildCommand: npm install && pip install yt-dlp
    startCommand: npm start
    envVars:
      - key: ALLOWED_ORIGIN
        value: "*"
      - key: NODE_ENV
        value: production
