// ── Static radio station data — split into separate chunk to reduce main bundle size
// These are only loaded when the user opens the Stream/Radio tab

export const NTS_STREAMS = [
  { id:'nts1', name:'NTS 1', desc:'Eclectic music, conversation and culture from around the world.', url:'https://stream-relay-geo.ntslive.net/stream',  genre:'Eclectic', color:'#ff4500' },
  { id:'nts2', name:'NTS 2', desc:'A second continuous stream of music and culture.',               url:'https://stream-relay-geo.ntslive.net/stream2', genre:'Eclectic', color:'#ff6500' },
  { id:'nts_lofi',  name:'NTS Lo-Fi',    desc:'Chilled lo-fi beats and downtempo sounds.',    url:'https://stream-relay-geo.ntslive.net/stream',  genre:'Lo-Fi',   color:'#22d3ee' },
  { id:'nts_hiphop',name:'NTS Hip-Hop',  desc:'Hip-hop, rap and r&b from around the world.',  url:'https://stream-relay-geo.ntslive.net/stream2', genre:'Hip-Hop', color:'#f59e0b' },
];

export const ICECAST_CURATED = [
  { id:'ice_bassdrive', name:'Bassdrive', desc:'Drum & Bass 24/7', url:'https://bassdrive.com/bassdrive.m3u', genre:'Drum & Bass', country:'US', color:'#8b5cf6' },
  { id:'ice_difm_chill', name:'SomaFM Thistle Radio', desc:'Celtic/folk/world music 24/7', url:'https://ice1.somafm.com/thistle-128-mp3', genre:'Chillout', country:'US', color:'#06b6d4' },
  { id:'ice_difm_trance', name:'SomaFM Space Station', desc:'Electronic/ambient space music 24/7', url:'https://ice1.somafm.com/spacestation-128-mp3', genre:'Trance', country:'US', color:'#8b5cf6' },
  { id:'ice_difm_house', name:'SomaFM Sonic Universe', desc:'Jazz fusion, funk & world music 24/7', url:'https://ice1.somafm.com/sonicuniverse-128-mp3', genre:'House', country:'US', color:'#f59e0b' },
  { id:'ice_difm_techno', name:'SomaFM Deep Space One', desc:'Deep ambient electronic 24/7', url:'https://ice1.somafm.com/deepspaceone-128-mp3', genre:'Techno', country:'US', color:'#ef4444' },
  { id:'ice_difm_dnb', name:'SomaFM Drone Zone', desc:'Atmospheric ambient drone music 24/7', url:'https://ice1.somafm.com/dronezone-128-mp3', genre:'D&B', country:'US', color:'#7c3aed' },
  { id:'ice_soma_groove', name:'SomaFM Groove Salad', desc:'Ambient/downtempo beats', url:'https://ice1.somafm.com/groovesalad-128-mp3', genre:'Ambient', country:'US', color:'#10b981' },
  { id:'ice_soma_secret', name:'SomaFM Secret Agent', desc:'Lounge/spy soundtrack', url:'https://ice1.somafm.com/secretagent-128-mp3', genre:'Lounge', country:'US', color:'#3b82f6' },
  { id:'ice_laut_jazz', name:'Jazz Radio', desc:'Jazz 24/7 from Germany', url:'https://stream.laut.fm/jazz', genre:'Jazz', country:'DE', color:'#7c3aed' },
  { id:'ice_laut_rock', name:'Classic Rock Radio', desc:'Classic Rock from Germany', url:'https://stream.laut.fm/classic-rock', genre:'Rock', country:'DE', color:'#ef4444' },
  { id:'ice_laut_metal', name:'Metal Radio', desc:'Heavy Metal 24/7', url:'https://stream.laut.fm/metal', genre:'Metal', country:'DE', color:'#1f2937' },
  { id:'ice_laut_pop', name:'Pop Radio', desc:'Pop hits from Germany', url:'https://stream.laut.fm/pop', genre:'Pop', country:'DE', color:'#f59e0b' },
  { id:'ice_laut_ambient', name:'Ambient Radio', desc:'Ambient music 24/7', url:'https://stream.laut.fm/ambient', genre:'Ambient', country:'DE', color:'#6366f1' },
  { id:'ice_laut_reggae', name:'Reggae Radio', desc:'Reggae & Dub 24/7', url:'https://stream.laut.fm/reggae', genre:'Reggae', country:'DE', color:'#16a34a' },
  { id:'ice_laut_classical', name:'Classical Radio', desc:'Classical music 24/7', url:'https://stream.laut.fm/classical', genre:'Classical', country:'DE', color:'#a16207' },
  { id:'ice_laut_hiphop', name:'Hip-Hop Radio', desc:'Hip-Hop & Rap 24/7', url:'https://stream.laut.fm/hiphop', genre:'Hip-Hop', country:'DE', color:'#dc2626' },
  { id:'ice_laut_world', name:'World Music Radio', desc:'Global world & folk music 24/7', url:'https://stream.laut.fm/world', genre:'World', country:'DE', color:'#f97316' },
  { id:'ice_laut_lofi', name:'Lo-Fi Beats Radio', desc:'Lo-Fi hip-hop & chill beats', url:'https://stream.laut.fm/lofi', genre:'Lo-Fi', country:'DE', color:'#8b5cf6' },
  { id:'ice_laut_folk', name:'Folk Radio', desc:'Folk & Americana 24/7', url:'https://stream.laut.fm/folk', genre:'Folk', country:'DE', color:'#a16207' },
  { id:'ice_laut_religi', name:'Islamic Radio', desc:'Murottal Al-Quran & nasyid 24/7', url:'https://stream.laut.fm/religious', genre:'Islamic', country:'ID', color:'#10b981' },
  { id:'ice_laut_dangdut', name:'Dangdut Radio', desc:'Dangdut & koplo Indonesia 24/7', url:'https://stream.laut.fm/dangdut', genre:'Dangdut', country:'ID', color:'#f97316' },
  { id:'ice_soma_poptron', name:'SomaFM PopTron', desc:'Electropop & indie pop 24/7', url:'https://ice1.somafm.com/poptron-128-mp3', genre:'Pop', country:'US', color:'#3b82f6' },
  { id:'ice_lofi_cafe', name:'Lo-Fi Café', desc:'Chilled lo-fi hip hop beats 24/7', url:'https://ice6.somafm.com/lush-128-mp3', genre:'Lo-Fi', country:'US', color:'#22d3ee' },
  { id:'ice_chillhop', name:'Chillhop Radio', desc:'Chillhop & lo-fi beats around the clock', url:'https://streams.ilovemusic.de/iloveradio17.mp3', genre:'Lo-Fi', country:'DE', color:'#06b6d4' },
  { id:'ice_soma_cliqhop', name:'SomaFM Cliqhop IDM', desc:'Blips, blops & lo-fi electronic wonders', url:'https://ice1.somafm.com/cliqhop-128-mp3', genre:'Lo-Fi', country:'US', color:'#22d3ee' },
  { id:'ice_hiphop_radio', name:'Hip-Hop Radio (Laut)', desc:'Hip-hop & rap hits 24/7', url:'https://stream.laut.fm/hiphop', genre:'Hip-Hop', country:'DE', color:'#f59e0b' },
  { id:'ice_illstreet', name:'SomaFM Ill Street Blues', desc:'Hip-hop, soul & gritty r&b', url:'https://ice1.somafm.com/illstreet-128-mp3', genre:'Hip-Hop', country:'US', color:'#f97316' },
  { id:'ice_rnb', name:'R&B Radio (Laut)', desc:'R&b, soul & smooth jams 24/7', url:'https://stream.laut.fm/rnb', genre:'Hip-Hop', country:'DE', color:'#ec4899' },
];

export const RADIO_PARADISE_CHANNELS = [
  { id:'rp_main', name:'Radio Paradise Main Mix', desc:'Eclectic mix of Rock, World, Classical & more — hand-curated, no ads', url:'https://stream.radioparadise.com/aac-128', genre:'Eclectic', country:'US', color:'#8b5cf6', image:'https://www.radioparadise.com/graphics/rp_320x320.png' },
  { id:'rp_mellow', name:'Radio Paradise Mellow Mix', desc:'Chill, ambient, acoustic — relaxed and soothing', url:'https://stream.radioparadise.com/mellow-128', genre:'Ambient', country:'US', color:'#06b6d4', image:'https://www.radioparadise.com/graphics/rp_320x320.png' },
  { id:'rp_rock', name:'Radio Paradise Rock Mix', desc:'Deep cuts and classic rock, hand-picked', url:'https://stream.radioparadise.com/rock-128', genre:'Rock', country:'US', color:'#ef4444', image:'https://www.radioparadise.com/graphics/rp_320x320.png' },
  { id:'rp_global', name:'Radio Paradise Global Mix', desc:'World music, jazz, folk, and global rhythms', url:'https://stream.radioparadise.com/global-128', genre:'World', country:'US', color:'#f59e0b', image:'https://www.radioparadise.com/graphics/rp_320x320.png' },
  { id:'rp_eclectic2', name:'Radio Paradise Eclectic Plus', desc:'Pop, rock, world — handpicked no ads', url:'https://stream.radioparadise.com/mp3-128', genre:'Pop', country:'US', color:'#a78bfa', image:'https://www.radioparadise.com/graphics/rp_320x320.png' },
];

export const FMSTREAM_CURATED = [
  { id:'fm_country', name:'Country Radio (laut.fm)', desc:'Country & Americana 24/7', url:'https://stream.laut.fm/country', genre:'Country', country:'DE', color:'#a16207', sourceLabel:'FM Stream' },
  { id:'fm_rnb', name:'R&B Radio (laut.fm)', desc:'R&B & Soul 24/7', url:'https://stream.laut.fm/rnb', genre:'R&B', country:'DE', color:'#f59e0b', sourceLabel:'FM Stream' },
  { id:'fm_electro', name:'Electronic Radio (laut.fm)', desc:'Electronic & Dance 24/7', url:'https://stream.laut.fm/electronic', genre:'Electronic', country:'DE', color:'#6366f1', sourceLabel:'FM Stream' },
  { id:'fm_80s', name:'80s Radio (laut.fm)', desc:'Best of 80s Pop & Rock', url:'https://stream.laut.fm/80s', genre:'80s', country:'DE', color:'#e11d48', sourceLabel:'FM Stream' },
  { id:'fm_90s', name:'90s Radio (laut.fm)', desc:'Best of 90s hits', url:'https://stream.laut.fm/90s', genre:'90s', country:'DE', color:'#7c3aed', sourceLabel:'FM Stream' },
  { id:'fm_lounge', name:'Lounge Radio (laut.fm)', desc:'Chillout & Lounge 24/7', url:'https://stream.laut.fm/lounge', genre:'Lounge', country:'DE', color:'#0891b2', sourceLabel:'FM Stream' },
  { id:'fm_salsa', name:'Salsa Radio (laut.fm)', desc:'Latin Salsa & Tropical 24/7', url:'https://stream.laut.fm/salsa', genre:'World', country:'DE', color:'#dc2626', sourceLabel:'FM Stream' },
  { id:'fm_gospel', name:'Gospel Radio (laut.fm)', desc:'Gospel & Christian 24/7', url:'https://stream.laut.fm/gospel', genre:'Gospel', country:'DE', color:'#d97706', sourceLabel:'FM Stream' },
  { id:'fm_punk', name:'Punk Radio (laut.fm)', desc:'Punk & Hardcore 24/7', url:'https://stream.laut.fm/punk', genre:'Rock', country:'DE', color:'#1f2937', sourceLabel:'FM Stream' },
  { id:'fm_smooth', name:'Smooth Jazz (laut.fm)', desc:'Smooth Jazz 24/7', url:'https://stream.laut.fm/smoothjazz', genre:'Jazz', country:'DE', color:'#5b21b6', sourceLabel:'FM Stream' },
  { id:'fm_piano', name:'Piano Radio (laut.fm)', desc:'Solo piano & instrumental', url:'https://stream.laut.fm/piano', genre:'Classical', country:'DE', color:'#a16207', sourceLabel:'FM Stream' },
  { id:'fm_hits', name:'Top Hits Radio (laut.fm)', desc:'Current Top Hits 24/7', url:'https://stream.laut.fm/tophits', genre:'Pop', country:'DE', color:'#3b82f6', sourceLabel:'FM Stream' },
  { id:'fm_hiphop', name:'Hip-Hop Radio (laut.fm)', desc:'Hip-Hop & Rap 24/7', url:'https://stream.laut.fm/hiphop', genre:'Hip-Hop', country:'DE', color:'#dc2626', sourceLabel:'FM Stream' },
  { id:'fm_jazz', name:'Jazz Radio (laut.fm)', desc:'Jazz 24/7', url:'https://stream.laut.fm/jazz', genre:'Jazz', country:'DE', color:'#7c3aed', sourceLabel:'FM Stream' },
  { id:'fm_rock', name:'Rock Radio (laut.fm)', desc:'Rock 24/7', url:'https://stream.laut.fm/rock', genre:'Rock', country:'DE', color:'#ef4444', sourceLabel:'FM Stream' },
  { id:'fm_classical', name:'Classical Radio (laut.fm)', desc:'Classical music 24/7', url:'https://stream.laut.fm/classical', genre:'Classical', country:'DE', color:'#a16207', sourceLabel:'FM Stream' },
  { id:'fm_world', name:'World Music Radio (laut.fm)', desc:'Global world music 24/7', url:'https://stream.laut.fm/world', genre:'World', country:'DE', color:'#f97316', sourceLabel:'FM Stream' },
  { id:'fm_reggae', name:'Reggae Radio (laut.fm)', desc:'Reggae & Dub 24/7', url:'https://stream.laut.fm/reggae', genre:'Reggae', country:'DE', color:'#16a34a', sourceLabel:'FM Stream' },
  { id:'fm_ambient', name:'Ambient Radio (laut.fm)', desc:'Ambient & Chillout 24/7', url:'https://stream.laut.fm/ambient', genre:'Ambient', country:'DE', color:'#6366f1', sourceLabel:'FM Stream' },
  { id:'fm_lofi', name:'Lo-Fi Radio (laut.fm)', desc:'Lo-Fi hip-hop beats & chill', url:'https://stream.laut.fm/lofi', genre:'Lo-Fi', country:'DE', color:'#8b5cf6', sourceLabel:'FM Stream' },
  { id:'fm_religi', name:'Religi Radio Indonesia', desc:'Musik religi Islami & nasyid 24/7', url:'https://stream.laut.fm/religious', genre:'Islamic', country:'ID', color:'#10b981', sourceLabel:'FM Stream' },
  { id:'fm_dangdut', name:'Dangdut Radio (laut.fm)', desc:'Dangdut & koplo Indonesia 24/7', url:'https://stream.laut.fm/dangdut', genre:'Dangdut', country:'ID', color:'#f97316', sourceLabel:'FM Stream' },
  { id:'fm_chillhop', name:'Chillhop FM (laut.fm)', desc:'Chillhop & downtempo grooves', url:'https://stream.laut.fm/chillhop', genre:'Lo-Fi', country:'DE', color:'#06b6d4', sourceLabel:'FM Stream' },
  { id:'fm_rap', name:'Rap Radio (laut.fm)', desc:'Rap & urban beats 24/7', url:'https://stream.laut.fm/rap', genre:'Hip-Hop', country:'DE', color:'#f97316', sourceLabel:'FM Stream' },
];

export const SHOUTCAST_CURATED = [
  { id:'sc_kexp', name:'KEXP 90.3 FM Seattle', desc:'Indie, alternative, world music — listener-funded', url:'https://kexp-mp3-128.streamguys1.com/kexp128.mp3', genre:'Indie', country:'US', color:'#10b981', sourceLabel:'Shoutcast' },
  { id:'sc_di_trance', name:'SomaFM Space Station', desc:'Electronic/ambient space music 24/7', url:'https://ice1.somafm.com/spacestation-128-mp3', genre:'Trance', country:'US', color:'#8b5cf6', sourceLabel:'Shoutcast' },
  { id:'sc_di_house', name:'SomaFM Sonic Universe', desc:'Jazz fusion & world music 24/7', url:'https://ice1.somafm.com/sonicuniverse-128-mp3', genre:'House', country:'US', color:'#f59e0b', sourceLabel:'Shoutcast' },
  { id:'sc_di_chillout', name:'SomaFM Thistle Radio', desc:'Celtic/folk/world music 24/7', url:'https://ice1.somafm.com/thistle-128-mp3', genre:'Chillout', country:'US', color:'#06b6d4', sourceLabel:'Shoutcast' },
  { id:'sc_di_drumandbass', name:'SomaFM Drone Zone', desc:'Atmospheric ambient drone 24/7', url:'https://ice1.somafm.com/dronezone-128-mp3', genre:'Drum & Bass', country:'US', color:'#7c3aed', sourceLabel:'Shoutcast' },
  { id:'sc_di_deephouse', name:'SomaFM Deep Space One', desc:'Deep ambient electronic 24/7', url:'https://ice1.somafm.com/deepspaceone-128-mp3', genre:'House', country:'US', color:'#f97316', sourceLabel:'Shoutcast' },
  { id:'sc_di_electro', name:'SomaFM Beat Blender', desc:'Electronic beat-driven music 24/7', url:'https://ice1.somafm.com/beatblender-128-mp3', genre:'Electronic', country:'US', color:'#ef4444', sourceLabel:'Shoutcast' },
  { id:'sc_di_ambient', name:'SomaFM Dark Zone', desc:'Dark ambient electronic 24/7', url:'https://ice1.somafm.com/darkzone-128-mp3', genre:'Ambient', country:'US', color:'#3b82f6', sourceLabel:'Shoutcast' },
  { id:'sc_di_dubstep', name:'SomaFM Dubstep Beyond', desc:'Dubstep & bass music 24/7', url:'https://ice3.somafm.com/dubstep-128-mp3', genre:'Electronic', country:'US', color:'#6366f1', sourceLabel:'Shoutcast' },
  { id:'sc_di_classical', name:'SomaFM Classical', desc:'Classical music 24/7', url:'https://ice1.somafm.com/classical-128-mp3', genre:'Classical', country:'US', color:'#a16207', sourceLabel:'Shoutcast' },
  { id:'sc_di_jazzandblues', name:'SomaFM Lush', desc:'Smooth jazz & vocal lounge 24/7', url:'https://ice1.somafm.com/lush-128-mp3', genre:'Jazz', country:'US', color:'#5b21b6', sourceLabel:'Shoutcast' },
  { id:'sc_di_reggae', name:'SomaFM Reggae Rec', desc:'Reggae & dancehall 24/7', url:'https://ice1.somafm.com/reggae-128-mp3', genre:'Reggae', country:'US', color:'#16a34a', sourceLabel:'Shoutcast' },
  { id:'sc_di_metal', name:'SomaFM Metal Detector', desc:'Heavy metal 24/7', url:'https://ice1.somafm.com/metal-128-mp3', genre:'Metal', country:'US', color:'#dc2626', sourceLabel:'Shoutcast' },
  { id:'sc_di_hiphop', name:'SomaFM Hip-Hop Spectrum', desc:'Hip-Hop & R&B 24/7', url:'https://ice1.somafm.com/hiphop-128-mp3', genre:'Hip-Hop', country:'US', color:'#d97706', sourceLabel:'Shoutcast' },
  { id:'sc_di_latinhouse', name:'SomaFM Salsa Station', desc:'Latin salsa & tropical 24/7', url:'https://ice1.somafm.com/salsa-128-mp3', genre:'World', country:'US', color:'#10b981', sourceLabel:'Shoutcast' },
  { id:'sc_wfmu', name:'WFMU Free Music Archive', desc:'Freeform radio from Jersey City NJ', url:'https://stream.wfmu.org/freeform/high/128kbps.mp3', genre:'Eclectic', country:'US', color:'#4b5563', sourceLabel:'Shoutcast' },
  { id:'sc_bbc_6music', name:'BBC Radio 6 Music', desc:'Alternative & indie from BBC', url:'https://stream.live.vc.bbcmedia.co.uk/bbc_6music', genre:'Indie', country:'GB', color:'#e11d48', sourceLabel:'Shoutcast' },
  { id:'sc_fip_fr', name:'FIP Radio France', desc:'Eclectic mix of world music & jazz', url:'https://icecast.radiofrance.fr/fip-midfi.mp3', genre:'World', country:'FR', color:'#3b82f6', sourceLabel:'Shoutcast' },
  { id:'sc_lofi_girl', name:'Lofi Girl Radio', desc:'Lo-Fi hip-hop beats to relax/study to', url:'https://stream.laut.fm/lofi', genre:'Lo-Fi', country:'FR', color:'#8b5cf6', sourceLabel:'Shoutcast' },
  { id:'sc_jazz_24', name:'Jazz24', desc:'Commercial-free jazz 24/7 — listener-supported', url:'https://live.amperwave.net/direct/ppm-jazz24aac-ibc1', genre:'Jazz', country:'US', color:'#7c3aed', sourceLabel:'Shoutcast' },
  { id:'sc_soma_pop', name:'SomaFM PopTron', desc:'Electropop & indie electronic pop', url:'https://ice1.somafm.com/poptron-128-mp3', genre:'Pop', country:'US', color:'#3b82f6', sourceLabel:'Shoutcast' },
  { id:'sc_soma_folk', name:'SomaFM Folk Forward', desc:'Indie folk, roots, Americana', url:'https://ice1.somafm.com/folkfwd-128-mp3', genre:'Folk', country:'US', color:'#a16207', sourceLabel:'Shoutcast' },
  { id:'sc_soma_cliqhop', name:'SomaFM Cliqhop IDM', desc:'IDM & electronic blips 24/7', url:'https://ice1.somafm.com/cliqhop-128-mp3', genre:'Electronic', country:'US', color:'#06b6d4', sourceLabel:'Shoutcast' },
  { id:'sc_soma_indie', name:'SomaFM Indie Pop Rocks', desc:'Indie pop & alternative 24/7', url:'https://ice1.somafm.com/indiepop-128-mp3', genre:'Indie', country:'US', color:'#10b981', sourceLabel:'Shoutcast' },
  { id:'sc_soma_world', name:'SomaFM DEF CON Radio', desc:'Electronic & world beats', url:'https://ice1.somafm.com/defcon-128-mp3', genre:'World', country:'US', color:'#f59e0b', sourceLabel:'Shoutcast' },
  { id:'sc_religi_id', name:'Radio Rodja 756 AM', desc:'Radio Islam Indonesia — murottal & kajian', url:'https://stream.radiorodja.com/rodja', genre:'Islamic', country:'ID', color:'#10b981', sourceLabel:'Shoutcast' },
  { id:'sc_religi2_id', name:'Radio Nurul Iman', desc:'Siaran Islam 24/7 Indonesia', url:'https://stream.laut.fm/islamicmusic', genre:'Islamic', country:'ID', color:'#059669', sourceLabel:'Shoutcast' },
  { id:'sc_dangdut_id', name:'Dangdut Mania Radio', desc:'Dangdut & koplo hits Indonesia 24/7', url:'https://stream.laut.fm/dangdut', genre:'Dangdut', country:'ID', color:'#f97316', sourceLabel:'Shoutcast' },
  { id:'sc_lofi_hip', name:'Lofi Hip Hop Radio', desc:'24/7 lo-fi hip hop beats to relax/study', url:'https://streams.ilovemusic.de/iloveradio17.mp3', genre:'Lo-Fi', country:'DE', color:'#22d3ee', sourceLabel:'Shoutcast' },
  { id:'sc_chillhop2', name:'Chillhop Music', desc:'Chillhop & lo-fi grooves nonstop', url:'https://stream.laut.fm/chillhop', genre:'Lo-Fi', country:'DE', color:'#06b6d4', sourceLabel:'Shoutcast' },
  { id:'sc_lofi_beats', name:'Lo-Fi Beats 24/7', desc:'Smooth lo-fi beats all day long', url:'https://ice1.somafm.com/cliqhop-128-mp3', genre:'Lo-Fi', country:'US', color:'#a78bfa', sourceLabel:'Shoutcast' },
  { id:'sc_hiphop2', name:'Hip-Hop Nation', desc:'Hip-hop & rap hits worldwide', url:'https://stream.laut.fm/hiphop', genre:'Hip-Hop', country:'US', color:'#f59e0b', sourceLabel:'Shoutcast' },
  { id:'sc_trap', name:'Trap Nation Radio', desc:'Trap, drill & urban beats 24/7', url:'https://stream.laut.fm/rap', genre:'Hip-Hop', country:'US', color:'#ef4444', sourceLabel:'Shoutcast' },
  { id:'sc_rnb2', name:'R&B Soul Station', desc:'Classic & contemporary r&b soul', url:'https://stream.laut.fm/rnb', genre:'Hip-Hop', country:'US', color:'#ec4899', sourceLabel:'Shoutcast' },
  { id:'sc_illstreet2', name:'SomaFM Ill Street Blues', desc:'Grittier hip-hop, soul & r&b', url:'https://ice1.somafm.com/illstreet-128-mp3', genre:'Hip-Hop', country:'US', color:'#f97316', sourceLabel:'Shoutcast' },
];
