export const STREAMING_PLATFORMS = [
  {
    id: 'ytmusic',
    name: 'YouTube',
    icon: '🔴',
    embedType: 'youtube',
    description: 'Cari & putar langsung dalam app via YouTube',
    color: '#FF0000',
    logo: null, // use inline SVG
    searchUrl: (q) => `https://www.youtube.com/results?search_query=${encodeURIComponent(q)}`,
    openUrl: 'https://www.youtube.com',
    hint: 'Cari lagu, artis, atau tempel link YouTube…',
  },
  {
    id: 'websearch',
    name: 'Web',
    icon: '🌐',
    embedType: 'websearch',
    description: 'SoundCloud · Spotify · Jamendo · FMA · ccMixter · archive.org & lainnya',
    color: '#6366f1',
    logo: null,
    openUrl: 'https://www.youtube.com',
    hint: 'Cari lagu/artis — SoundCloud, Spotify, Jamendo, Vimeo, Audiomack, Mixcloud…',
  },
  {
    id: 'radio',
    name: 'Radio',
    icon: '📻',
    embedType: 'radio',
    description: 'Radio populer dunia · 10 negara populer · genre lengkap',
    color: '#f59e0b',
    logo: null,
    openUrl: 'https://www.radio.net',
    hint: 'Pilih negara, genre, lalu stasiun…',
    countries: [
      {
        id: 'us', name: 'Amerika Serikat', flag: '🇺🇸', color: '#3b82f6',
        genres: [
          { id: 'pop', name: 'Pop / Top 40', icon: '🎵', color: '#3b82f6', stations: [
            { id: 'z100', name: 'Z100 New York (iHeart)', city: 'New York', url: 'https://stream.revma.ihrhls.com/zc406' },
            { id: 'kiis', name: 'KIIS FM Los Angeles', city: 'Los Angeles', url: 'https://stream.revma.ihrhls.com/zc1714' },
            { id: 'hot97', name: 'HOT 97 Hip-Hop', city: 'New York', url: 'https://ice9.securenetsystems.net/HOT97' },
            { id: 'top40-sf', name: 'Wild 94.9 SF', city: 'San Francisco', url: 'https://stream.revma.ihrhls.com/zc258' },
            { id: 'y100-miami', name: 'Y100 Miami', city: 'Miami', url: 'https://stream.revma.ihrhls.com/zc1178' },
            { id: 'power106', name: 'Power 106 LA (Hip-Hop/RnB)', city: 'Los Angeles', url: 'https://stream.revma.ihrhls.com/zc1866' },
          ]},
          { id: 'rock', name: 'Rock / Alternative', icon: '🎸', color: '#ef4444', stations: [
            { id: 'kroq', name: 'KROQ Alt Rock LA', city: 'Los Angeles', url: 'https://stream.revma.ihrhls.com/zc2922' },
            { id: 'metal-soma', name: 'Metal Detector (SomaFM)', city: 'San Francisco', url: 'https://ice1.somafm.com/metal-128-mp3' },
            { id: 'indie-pop', name: 'Indie Pop Rocks (SomaFM)', city: 'San Francisco', url: 'https://ice1.somafm.com/indiepop-128-mp3' },
            { id: 'folkfwd', name: 'Folk Forward (SomaFM)', city: 'San Francisco', url: 'https://ice1.somafm.com/folkfwd-128-mp3' },
            { id: 'punk-soma', name: 'Doomed (SomaFM Dark/Metal)', city: 'San Francisco', url: 'https://ice1.somafm.com/doomed-128-mp3' },
            { id: 'thetrip-soma', name: 'The Trip (SomaFM Psychedelic)', city: 'San Francisco', url: 'https://ice1.somafm.com/thetrip-128-mp3' },
          ]},
          { id: 'country', name: 'Country / Americana', icon: '🤠', color: '#92400e', stations: [
            { id: 'wsm', name: 'WSM 650 Nashville', city: 'Nashville', url: 'https://stream.revma.ihrhls.com/zc3226' },
            { id: 'nash-fm', name: 'Nash FM Country', city: 'National', url: 'https://stream.revma.ihrhls.com/zc3050' },
            { id: 'boot-liquor', name: 'Boot Liquor (Americana)', city: 'San Francisco', url: 'https://ice1.somafm.com/bootliquor-128-mp3' },
            { id: 'folkfwd2', name: 'Folk Forward (SomaFM)', city: 'San Francisco', url: 'https://ice1.somafm.com/folkfwd-128-mp3' },
            { id: 'country-bbq', name: 'Lonestar (Country BBQ)', city: 'Texas', url: 'https://stream.zeno.fm/lonestar-country' },
            { id: 'whiskey-soma', name: 'Whiskey Before Breakfast (SomaFM)', city: 'San Francisco', url: 'https://ice1.somafm.com/Whiskeybeforebr-128-mp3' },
          ]},
          { id: 'jazz', name: 'Jazz / Blues / Soul', icon: '🎷', color: '#7c3aed', stations: [
            { id: 'wbgo', name: 'WBGO Jazz 88.3 FM', city: 'New York', url: 'https://wbgo.streamguys1.com/wbgo128.mp3' },
            { id: 'sonicuniverse', name: 'Sonic Universe (SomaFM)', city: 'San Francisco', url: 'https://ice1.somafm.com/sonicuniverse-128-mp3' },
            { id: 'jazz-soma', name: 'Jazz (SomaFM)', city: 'San Francisco', url: 'https://ice1.somafm.com/jazz-128-mp3' },
            { id: 'blues-soma', name: 'Illinois Street Lounge (Blues)', city: 'San Francisco', url: 'https://ice1.somafm.com/illstreet-128-mp3' },
            { id: 'sf1033', name: 'SF in SF (Jazz/Talk)', city: 'San Francisco', url: 'https://ice1.somafm.com/sf1033-128-mp3' },
            { id: 'groove-salad', name: 'Groove Salad (SomaFM)', city: 'San Francisco', url: 'https://ice1.somafm.com/groovesalad-128-mp3' },
          ]},
          { id: 'hiphop', name: 'Hip-Hop / R&B', icon: '🎤', color: '#f59e0b', stations: [
            { id: 'soulful-soma', name: 'SoulfulSide (SomaFM)', city: 'San Francisco', url: 'https://ice1.somafm.com/SoulfulSide-128-mp3' },
            { id: 'hiphop-zeno', name: 'Hip-Hop Radio USA', city: 'New York', url: 'https://stream.zeno.fm/hiphop-usa' },
            { id: 'oldschool-hiphop', name: 'Old School Hip-Hop', city: 'Online', url: 'https://stream.laut.fm/oldschoolhiphop' },
            { id: 'rnb-zeno', name: 'R&B United States', city: 'Atlanta', url: 'https://stream.zeno.fm/rnb-united-states' },
            { id: 'trap-radio', name: 'Trap Nation Radio', city: 'Online', url: 'https://stream.zeno.fm/trap-nation' },
            { id: 'rap-us', name: 'Rap Radio USA', city: 'Online', url: 'https://stream.laut.fm/rap' },
          ]},
          { id: 'electronic', name: 'Electronic / Dance', icon: '🎧', color: '#8b5cf6', stations: [
            { id: 'deptstore-soma', name: 'Dept. Store (SomaFM Lo-Fi)', city: 'San Francisco', url: 'https://ice1.somafm.com/deptstore-128-mp3' },
            { id: 'cliqhop', name: 'cliqhop idm (SomaFM)', city: 'San Francisco', url: 'https://ice1.somafm.com/cliqhop-128-mp3' },
            { id: 'edm-radio', name: 'EDM Radio US', city: 'New York', url: 'https://stream.zeno.fm/edm-radio' },
            { id: 'house-nation', name: 'House Nation Radio', city: 'Chicago', url: 'https://stream.laut.fm/house' },
            { id: 'dubstep-radio', name: 'Dubstep Radio US', city: 'Online', url: 'https://stream.zeno.fm/dubstep-radio' },
            { id: 'techno-us', name: 'Techno USA (Laut.fm)', city: 'Online', url: 'https://stream.laut.fm/techno' },
          ]},
          { id: 'news', name: 'News / Talk', icon: '📰', color: '#64748b', stations: [
            { id: 'npr', name: 'NPR News Now', city: 'National', url: 'https://npr-ice.streamguys1.com/live.mp3' },
            { id: 'wtop', name: 'WTOP News 103.5', city: 'Washington DC', url: 'https://stream.revma.ihrhls.com/zc2754' },
            { id: 'kcbs', name: 'KCBS News Radio', city: 'San Francisco', url: 'https://stream.revma.ihrhls.com/zc578' },
            { id: 'wbbm', name: 'WBBM Newsradio', city: 'Chicago', url: 'https://stream.revma.ihrhls.com/zc402' },
            { id: 'kogo', name: 'KOGO News San Diego', city: 'San Diego', url: 'https://stream.revma.ihrhls.com/zc2474' },
            { id: 'bbc-world-us', name: 'BBC World Service', city: 'London/National', url: 'https://stream.live.vc.bbcmedia.co.uk/bbc_world_service' },
          ]},
        ],
      },
      {
        id: 'uk', name: 'Inggris', flag: '🇬🇧', color: '#e11d48',
        genres: [
          { id: 'pop', name: 'Pop / Chart Hits', icon: '🎵', color: '#e11d48', stations: [
            { id: 'bbc-r1', name: 'BBC Radio 1', city: 'London', url: 'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_one' },
            { id: 'heart', name: 'Heart FM', city: 'London', url: 'https://media-ice.musicradio.com/HeartUKMP3' },
            { id: 'capital', name: 'Capital FM', city: 'London', url: 'https://media-ice.musicradio.com/CapitalUKMP3' },
            { id: 'absolute', name: 'Absolute Radio', city: 'London', url: 'https://media-ice.musicradio.com/AbsoluteRadioMP3' },
            { id: 'magic-uk', name: 'Magic FM', city: 'London', url: 'https://media-ice.musicradio.com/MagicUKMP3' },
            { id: 'bbc-r2', name: 'BBC Radio 2 (Easy Listening)', city: 'London', url: 'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_two' },
          ]},
          { id: 'rock', name: 'Rock / Alternative', icon: '🎸', color: '#dc2626', stations: [
            { id: 'kerrang', name: 'Kerrang! Radio', city: 'Birmingham', url: 'https://media-ice.musicradio.com/KerrangMP3' },
            { id: 'planet-rock', name: 'Planet Rock', city: 'London', url: 'https://media-ice.musicradio.com/PlanetRockMP3' },
            { id: 'absolute-rock', name: 'Absolute Radio Rock', city: 'London', url: 'https://media-ice.musicradio.com/AbsoluteRadioRockMP3' },
            { id: 'radio-x', name: 'Radio X', city: 'London', url: 'https://media-ice.musicradio.com/RadioXUKMP3' },
            { id: 'absolute-80s', name: 'Absolute 80s', city: 'London', url: 'https://media-ice.musicradio.com/Absolute80sMP3' },
            { id: 'absolute-90s', name: 'Absolute 90s', city: 'London', url: 'https://media-ice.musicradio.com/Absolute90sMP3' },
          ]},
          { id: 'classical', name: 'Classical / Jazz', icon: '🎻', color: '#7c3aed', stations: [
            { id: 'bbc-r3', name: 'BBC Radio 3 (Classical)', city: 'London', url: 'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_three' },
            { id: 'classic-fm', name: 'Classic FM', city: 'London', url: 'https://media-ice.musicradio.com/ClassicFMMP3' },
            { id: 'smooth', name: 'Smooth Radio', city: 'London', url: 'https://media-ice.musicradio.com/SmoothUKMP3' },
            { id: 'jazz-fm', name: 'Jazz FM', city: 'London', url: 'https://streaming.radio.co/s2a648cde8/listen' },
            { id: 'lyric-fm', name: 'Lyric FM (Ireland)', city: 'Dublin', url: 'https://icecast.rte.ie/lyricfm.mp3' },
            { id: 'bbc-r3-jazz', name: 'BBC Radio 3 Late Jn (Jazz)', city: 'London', url: 'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_three' },
          ]},
          { id: 'dance', name: 'Dance / Electronic', icon: '🎧', color: '#8b5cf6', stations: [
            { id: 'kiss-uk', name: 'KISS FM UK', city: 'London', url: 'https://media-ice.musicradio.com/KISSUKHD' },
            { id: 'capital-xtra', name: 'Capital XTRA', city: 'London', url: 'https://media-ice.musicradio.com/CapitalXtraMP3' },
            { id: 'kiss-fresh', name: 'KISS Fresh', city: 'London', url: 'https://media-ice.musicradio.com/KISSFRESHMP3' },
            { id: 'magic-chilled', name: 'Magic Chilled', city: 'London', url: 'https://media-ice.musicradio.com/MagicChilledMP3' },
            { id: 'radio-1xtra', name: 'BBC Radio 1Xtra (Urban)', city: 'London', url: 'https://stream.live.vc.bbcmedia.co.uk/bbc_1xtra' },
            { id: 'bbc-r6', name: 'BBC Radio 6 Music (Alternative)', city: 'London', url: 'https://stream.live.vc.bbcmedia.co.uk/bbc_6music' },
          ]},
          { id: 'hiphop-uk', name: 'Hip-Hop / Grime / RnB', icon: '🎤', color: '#f59e0b', stations: [
            { id: 'bbc-1xtra-uk', name: 'BBC Radio 1Xtra', city: 'London', url: 'https://stream.live.vc.bbcmedia.co.uk/bbc_1xtra' },
            { id: 'rinse-fm', name: 'Rinse FM (Grime/Electronic)', city: 'London', url: 'https://stream.zeno.fm/rinse-fm-uk' },
            { id: 'complex-uk', name: 'Complex UK Urban', city: 'London', url: 'https://stream.zeno.fm/complex-uk' },
            { id: 'kiss-uk-urban', name: 'KISS FM UK Urban', city: 'London', url: 'https://media-ice.musicradio.com/KISSUKHD' },
            { id: 'reprezent', name: 'Reprezent Radio 107.3 FM', city: 'London', url: 'https://stream.zeno.fm/reprezent-uk' },
            { id: 'uk-rnb', name: 'UK R&B Station (Laut.fm)', city: 'Online', url: 'https://stream.laut.fm/rnb' },
          ]},
          { id: 'oldies', name: 'Oldies / Heritage', icon: '🕰️', color: '#d97706', stations: [
            { id: 'magic-uk2', name: 'Magic Radio (Gold Hits)', city: 'London', url: 'https://media-ice.musicradio.com/MagicUKMP3' },
            { id: 'gold-uk', name: 'Gold Radio UK', city: 'London', url: 'https://media-ice.musicradio.com/GoldMP3' },
            { id: 'greatest-hits', name: 'Greatest Hits Radio', city: 'London', url: 'https://media-ice.musicradio.com/GreatestHitsMP3' },
            { id: 'bbc-r4extra', name: 'BBC Radio 4 Extra (Vintage)', city: 'London', url: 'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_four_extra' },
            { id: 'absolute-classic', name: 'Absolute Classic Rock', city: 'London', url: 'https://media-ice.musicradio.com/AbsoluteClassicRockMP3' },
            { id: 'bbc-sounds-uk', name: 'BBC Radio 2 (Pop Oldies)', city: 'London', url: 'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_two' },
          ]},
          { id: 'news', name: 'News / Talk', icon: '📰', color: '#64748b', stations: [
            { id: 'bbc-world', name: 'BBC World Service', city: 'London', url: 'https://stream.live.vc.bbcmedia.co.uk/bbc_world_service' },
            { id: 'bbc-r4', name: 'BBC Radio 4', city: 'London', url: 'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_fourfm' },
            { id: 'lbc', name: 'LBC News', city: 'London', url: 'https://media-ice.musicradio.com/LBCMP3' },
            { id: 'times-radio', name: 'Times Radio', city: 'London', url: 'https://timesradio.wireless.radio/stream' },
            { id: 'bbc-r5', name: 'BBC Radio 5 Live', city: 'London', url: 'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_five_live' },
            { id: 'talkradio-uk', name: 'Talk Radio UK', city: 'London', url: 'https://media-ice.musicradio.com/TalkRadioUKMP3' },
          ]},
        ],
      },
      {
        id: 'fr', name: 'Prancis', flag: '🇫🇷', color: '#3b82f6',
        genres: [
          { id: 'pop', name: 'Pop / Variété', icon: '🎵', color: '#3b82f6', stations: [
            { id: 'nrj', name: 'NRJ', city: 'Paris', url: 'https://scdn.nrjaudio.fm/adwz2/fr/30001/mp3_128.mp3' },
            { id: 'nostalgie', name: 'Nostalgie', city: 'Paris', url: 'https://scdn.nrjaudio.fm/adwz2/fr/30700/mp3_128.mp3' },
            { id: 'cherie', name: 'Chérie FM', city: 'Paris', url: 'https://scdn.nrjaudio.fm/adwz2/fr/30201/mp3_128.mp3' },
            { id: 'france-inter', name: 'France Inter', city: 'Paris', url: 'https://icecast.radiofrance.fr/franceinter-midfi.mp3' },
            { id: 'europe1', name: 'Europe 1', city: 'Paris', url: 'https://stream.europe1.fr/europe1.mp3' },
            { id: 'rtl-fr', name: 'RTL France', city: 'Paris', url: 'https://streaming.radio.rtl.fr/rtl-1-44-96' },
          ]},
          { id: 'dance', name: 'Dance / Électro', icon: '🎧', color: '#8b5cf6', stations: [
            { id: 'fip-electro', name: 'FIP Électro', city: 'Paris', url: 'https://icecast.radiofrance.fr/fipelectro-midfi.mp3' },
            { id: 'fip', name: 'FIP (Jazz/Électro/World)', city: 'Paris', url: 'https://icecast.radiofrance.fr/fip-midfi.mp3' },
            { id: 'radio-meuh', name: 'Radio Meuh (Electro/Indie)', city: 'Paris', url: 'https://radiomeuh.ice.infomaniak.ch/radiomeuh-128.mp3' },
            { id: 'mouv', name: "Mouv' (Urban/Electro)", city: 'Paris', url: 'https://icecast.radiofrance.fr/mouv-midfi.mp3' },
            { id: 'fip-groove', name: 'FIP Groove', city: 'Paris', url: 'https://icecast.radiofrance.fr/fipgroove-midfi.mp3' },
            { id: 'fun-radio', name: 'Fun Radio (Dance/RnB)', city: 'Paris', url: 'https://stream.funradio.fr/fun-1-48-128' },
          ]},
          { id: 'classical', name: 'Classique / Jazz', icon: '🎻', color: '#7c3aed', stations: [
            { id: 'france-musique', name: 'France Musique', city: 'Paris', url: 'https://icecast.radiofrance.fr/francemusique-midfi.mp3' },
            { id: 'radio-classique', name: 'Radio Classique', city: 'Paris', url: 'https://radioclassique.ice.infomaniak.ch/radioclassique-high' },
            { id: 'tsfjazz', name: 'TSF Jazz', city: 'Paris', url: 'https://tsfjazz.ice.infomaniak.ch/tsfjazz-high' },
            { id: 'fip-jazz', name: 'FIP Jazz', city: 'Paris', url: 'https://icecast.radiofrance.fr/fipjazz-midfi.mp3' },
            { id: 'fip-world', name: 'FIP Monde (World Music)', city: 'Paris', url: 'https://icecast.radiofrance.fr/fipworld-midfi.mp3' },
            { id: 'fip-reggae', name: 'FIP Reggae', city: 'Paris', url: 'https://icecast.radiofrance.fr/fipreggae-midfi.mp3' },
          ]},
          { id: 'rnb', name: 'R&B / Hip-Hop / Urban', icon: '🎤', color: '#f59e0b', stations: [
            { id: 'skyrock', name: 'Skyrock (Hip-Hop/RnB)', city: 'Paris', url: 'https://stream.skyrock.com/skyrock-128.mp3' },
            { id: 'mouv2', name: "Mouv' 100% Urban", city: 'Paris', url: 'https://icecast.radiofrance.fr/mouv-midfi.mp3' },
            { id: 'rfm', name: 'RFM (Soul/Variété)', city: 'Paris', url: 'https://rfm.ice.infomaniak.ch/rfm-high.mp3' },
            { id: 'virgin-radio', name: 'Virgin Radio France', city: 'Paris', url: 'https://virgin.ice.infomaniak.ch/virgin-high.mp3' },
            { id: 'rap-fr', name: 'Rap Radio France (Laut.fm)', city: 'Paris', url: 'https://stream.laut.fm/rap' },
            { id: 'oui-fm', name: 'OUI FM (Rock/Urban)', city: 'Paris', url: 'https://ouifm.ice.infomaniak.ch/ouifm-high.mp3' },
          ]},
          { id: 'rock-fr', name: 'Rock / Metal', icon: '🎸', color: '#dc2626', stations: [
            { id: 'riffx', name: 'RIFFX (Metal/Punk)', city: 'Paris', url: 'https://stream.riffx.fr/riffx-128.mp3' },
            { id: 'nova-fr', name: 'Radio Nova (Funk/Soul/Indie)', city: 'Paris', url: 'https://novazz.ice.infomaniak.ch/nova-high.mp3' },
            { id: 'radio-metal-fr', name: 'Radio Metal France', city: 'Lyon', url: 'https://stream.zeno.fm/radiometal-fr' },
            { id: 'oui-rock', name: 'OUI FM Rock', city: 'Paris', url: 'https://ouifm.ice.infomaniak.ch/ouifm-high.mp3' },
            { id: 'heavy1-fr', name: 'Heavy One (Metal/Hardcore)', city: 'Paris', url: 'https://stream.laut.fm/heavy1' },
            { id: 'fip-pop', name: 'FIP Pop (Indie/Altpop)', city: 'Paris', url: 'https://icecast.radiofrance.fr/fippop-midfi.mp3' },
          ]},
          { id: 'chanson', name: 'Chanson Française', icon: '🇫🇷', color: '#1d4ed8', stations: [
            { id: 'france-bleu', name: 'France Bleu (Chanson/Régional)', city: 'Paris', url: 'https://icecast.radiofrance.fr/francebleu-midfi.mp3' },
            { id: 'rire-chansons', name: 'Rire et Chansons', city: 'Paris', url: 'https://scdn.nrjaudio.fm/adwz2/fr/30401/mp3_128.mp3' },
            { id: 'chanson-classique', name: 'Chanson Classique (Nostalgie)', city: 'Paris', url: 'https://scdn.nrjaudio.fm/adwz2/fr/30700/mp3_128.mp3' },
            { id: 'vibration-fr', name: 'Vibration FM', city: 'Paris', url: 'https://stream.vibration.fr/vibration-128.mp3' },
            { id: 'radio-bleue', name: 'Radio Bleue (Variété/Chanson)', city: 'Paris', url: 'https://stream.zeno.fm/radio-bleue-fr' },
            { id: 'voltage-fr', name: 'Voltage FM', city: 'Paris', url: 'https://stream.voltage.fr/voltage-128.mp3' },
          ]},
          { id: 'news', name: 'Info / Actualités', icon: '📰', color: '#64748b', stations: [
            { id: 'france-info', name: 'Franceinfo', city: 'Paris', url: 'https://icecast.radiofrance.fr/franceinfo-midfi.mp3' },
            { id: 'france-culture', name: 'France Culture', city: 'Paris', url: 'https://icecast.radiofrance.fr/franceculture-midfi.mp3' },
            { id: 'rfi', name: 'RFI Monde', city: 'Paris', url: 'https://icecast.radiofrance.fr/rfi-midfi.mp3' },
            { id: 'bfm-radio', name: 'BFM Radio', city: 'Paris', url: 'https://bfmradio.ice.infomaniak.ch/bfmradio-high.mp3' },
            { id: 'rmc', name: 'RMC Info', city: 'Paris', url: 'https://rmc.bfmtv.com/rmc-128.mp3' },
            { id: 'france-inter-news', name: 'France Inter (News/Talk)', city: 'Paris', url: 'https://icecast.radiofrance.fr/franceinter-midfi.mp3' },
          ]},
        ],
      },
      {
        id: 'de', name: 'Jerman', flag: '🇩🇪', color: '#fbbf24',
        genres: [
          { id: 'pop', name: 'Pop / Charts', icon: '🎵', color: '#fbbf24', stations: [
            { id: 'antenne', name: 'Antenne Bayern', city: 'Munich', url: 'https://s1-webradio.antenne.de/antenne' },
            { id: 'bigfm', name: 'BigFM Deutschland', city: 'Stuttgart', url: 'https://streams.bigfm.de/bigfm-deutschland-128-mp3' },
            { id: 'hit-ffh', name: 'Hit Radio FFH', city: 'Frankfurt', url: 'https://streams.ffh.de/radioffh/mp3/256' },
            { id: 'nrj-de', name: 'Energy Radio', city: 'München', url: 'https://scdn.nrjaudio.fm/adwz2/de/33001/mp3_128.mp3' },
            { id: 'radio-bob', name: 'Radio BOB! (Rock/Pop)', city: 'Kassel', url: 'https://streams.radiobob.de/bob-national/mp3-192/streams.radiobob.de/' },
            { id: 'hr3-de', name: 'HR3 (Pop/80s)', city: 'Frankfurt', url: 'https://hr-hr3-live.cast.addradio.de/hr/hr3/live/mp3/128/stream.mp3' },
          ]},
          { id: 'dance', name: 'Electronic / Dance', icon: '🎧', color: '#8b5cf6', stations: [
            { id: 'sunshine-live', name: 'sunshine live (Techno/House)', city: 'Mannheim', url: 'https://stream.sunshine-live.de/live/mp3-128' },
            { id: 'flux-deep', name: 'FluxFM Chillhop', city: 'Berlin', url: 'https://streams.fluxfm.de/Chillhop/mp3-320/streams.fluxfm.de/' },
            { id: 'dance-de', name: 'FluxFM Dance', city: 'Berlin', url: 'https://streams.fluxfm.de/Dance/mp3-128/streams.fluxfm.de/' },
            { id: 'bigfm-dance', name: 'BigFM Dance', city: 'Stuttgart', url: 'https://streams.bigfm.de/bigfm-dance-128-mp3' },
            { id: 'clubbing-fluxfm', name: 'FluxFM Clubbing', city: 'Berlin', url: 'https://streams.fluxfm.de/Clubbing/mp3-128/streams.fluxfm.de/' },
            { id: 'techno-de', name: 'Techno Station DE (Laut.fm)', city: 'Berlin', url: 'https://stream.laut.fm/techno' },
          ]},
          { id: 'classical', name: 'Klassik / Kultur', icon: '🎻', color: '#7c3aed', stations: [
            { id: 'deutschlandradio', name: 'Deutschlandradio Kultur', city: 'Berlin', url: 'https://st01.sslstream.dlf.de/dlf/01/128/mp3/stream.mp3' },
            { id: 'dlf', name: 'Deutschlandfunk', city: 'Cologne', url: 'https://st02.sslstream.dlf.de/dlf/02/128/mp3/stream.mp3' },
            { id: 'wdr3', name: 'WDR 3 (Klassik/Kultur)', city: 'Cologne', url: 'https://wdr-wdr3-live.icecastssl.wdr.de/wdr/wdr3/live/mp3/128/stream.mp3' },
            { id: 'br-klassik', name: 'BR-Klassik', city: 'Munich', url: 'https://dispatcher.rndfnk.com/br/brklassik/live/mp3/low' },
            { id: 'rbb-kultur', name: 'rbb Kulturradio', city: 'Berlin', url: 'https://rbb-kulturradio-live.sslcast.addradio.de/rbb/kulturradio/live/mp3/128/stream.mp3' },
            { id: 'ndr-kultur', name: 'NDR Kultur', city: 'Hamburg', url: 'https://ndr-ndrkultur-live.sslcast.addradio.de/ndr/ndrkultur/live/mp3/128/stream.mp3' },
          ]},
          { id: 'schlager', name: 'Schlager / Volksmusik', icon: '🍺', color: '#d97706', stations: [
            { id: 'schlager-radio', name: 'Schlager Radio', city: 'Online', url: 'https://stream.laut.fm/schlager' },
            { id: 'antenne-schlager', name: 'Antenne Bayern Schlager', city: 'Munich', url: 'https://s4-webradio.antenne.de/schlager' },
            { id: 'bigfm-schlager', name: 'BigFM Schlager', city: 'Stuttgart', url: 'https://streams.bigfm.de/bigfm-schlager-128-mp3' },
            { id: 'volksmusik', name: 'Antenne Bayern Volksmusik', city: 'Munich', url: 'https://s5-webradio.antenne.de/volksmusik' },
            { id: 'mdr-jump', name: 'MDR Jump (Schlager/Pop)', city: 'Leipzig', url: 'https://mdr-jump-live.icecastssl.mdr.de/mdr/jump/live/mp3/128/stream.mp3' },
            { id: 'schlagerplanet', name: 'Schlagerplanet Radio', city: 'Online', url: 'https://stream.zeno.fm/schlagerplanet' },
          ]},
          { id: 'rock-de', name: 'Rock / Metal', icon: '🎸', color: '#ef4444', stations: [
            { id: 'metal1-de', name: 'Metal 1 Radio', city: 'Online', url: 'https://stream.metal1.eu/metal1' },
            { id: 'radiobob-metal', name: 'Radio BOB! Metal', city: 'Kassel', url: 'https://streams.radiobob.de/bob-metal/mp3-128/streams.radiobob.de/' },
            { id: 'rock-antenne', name: 'Rock Antenne Bayern', city: 'Munich', url: 'https://s5-webradio.antenne.de/rock-antenne' },
            { id: 'radio-fritz', name: 'Radio Fritz (Alternative)', city: 'Berlin', url: 'https://fritz-live.sslcast.addradio.de/fritz/live/mp3/128/stream.mp3' },
            { id: 'flux-berlin', name: 'FluxFM Berlin (Indie Rock)', city: 'Berlin', url: 'https://streams.fluxfm.de/fluxfm/mp3-128/streams.fluxfm.de/' },
            { id: 'bigfm-rock', name: 'BigFM Rock', city: 'Stuttgart', url: 'https://streams.bigfm.de/bigfm-rock-128-mp3' },
          ]},
          { id: 'hiphop-de', name: 'Hip-Hop / RnB DE', icon: '🎤', color: '#10b981', stations: [
            { id: 'bigfm-hiphop', name: 'BigFM Hip-Hop', city: 'Stuttgart', url: 'https://streams.bigfm.de/bigfm-hiphop-128-mp3' },
            { id: 'energy-hiphop', name: 'Energy Hip-Hop DE', city: 'München', url: 'https://scdn.nrjaudio.fm/adwz2/de/33009/mp3_128.mp3' },
            { id: 'rap-de', name: 'Rap Radio Deutschland', city: 'Berlin', url: 'https://stream.laut.fm/rapde' },
            { id: 'rnb-de', name: 'R&B Radio DE (Zeno)', city: 'Berlin', url: 'https://stream.zeno.fm/rnb-deutschland' },
            { id: 'flavor-de', name: 'Flavor Radio DE (Urban)', city: 'Hamburg', url: 'https://stream.zeno.fm/flavor-radio-de' },
            { id: 'flux-hiphop', name: 'FluxFM Hip-Hop', city: 'Berlin', url: 'https://streams.fluxfm.de/HipHop/mp3-128/streams.fluxfm.de/' },
          ]},
          { id: 'news', name: 'News / Nachrichten', icon: '📰', color: '#64748b', stations: [
            { id: 'inforadio', name: 'Inforadio rbb', city: 'Berlin', url: 'https://rbb-inforadio-live.sslcast.addradio.de/rbb/inforadio/live/mp3/128/stream.mp3' },
            { id: 'b5-aktuell', name: 'Bayern 5 aktuell', city: 'Munich', url: 'https://dispatcher.rndfnk.com/br/br5/live/mp3/low' },
            { id: 'wdr5', name: 'WDR 5 (News/Talk)', city: 'Cologne', url: 'https://wdr-wdr5-live.icecastssl.wdr.de/wdr/wdr5/live/mp3/128/stream.mp3' },
            { id: 'swr-aktuell', name: 'SWR Aktuell', city: 'Stuttgart', url: 'https://liveradio.swr.de/sw282p3/swr-aktuell/play.mp3' },
            { id: 'ndr-info', name: 'NDR Info', city: 'Hamburg', url: 'https://ndr-ndrinfo-live.sslcast.addradio.de/ndr/ndrinfo/live/mp3/128/stream.mp3' },
            { id: 'deutschlandradio-news', name: 'Deutschlandfunk Nova', city: 'Cologne', url: 'https://st03.sslstream.dlf.de/dlf/03/128/mp3/stream.mp3' },
          ]},
        ],
      },
      {
        id: 'id', name: 'Indonesia', flag: '🇮🇩', color: '#ef4444',
        genres: [
          { id: 'pop', name: 'Pop / Top 40', icon: '🎵', color: '#ef4444', stations: [
            { id: 'prambors', name: 'Prambors FM', city: 'Jakarta', url: 'https://n06.radiojar.com/prambors.mp3' },
            { id: 'gen', name: 'Gen FM Jakarta', city: 'Jakarta', url: 'https://n06.radiojar.com/genfm.mp3' },
            { id: 'jak-fm', name: 'Jak FM', city: 'Jakarta', url: 'https://edge.iono.fm/c/546/icecast.audio' },
            { id: 'female', name: 'Female Radio Jakarta', city: 'Jakarta', url: 'https://stream.zeno.fm/y3u7jfkhc0zuv' },
            { id: 'ria-fm', name: 'Ria FM Jakarta', city: 'Jakarta', url: 'https://stream.zeno.fm/riafm-jakarta' },
            { id: 'trenda-fm', name: 'Trenda 97.5 FM', city: 'Jakarta', url: 'https://stream.zeno.fm/trendafm975' },
          ]},
          { id: 'dangdut', name: 'Dangdut / Koplo', icon: '🥁', color: '#f59e0b', stations: [
            { id: 'dangdut-id', name: 'Radio Dangdut Indonesia', city: 'Jakarta', url: 'https://edge.iono.fm/c/562/icecast.audio' },
            { id: 'dangdut3', name: 'Nada FM (Dangdut)', city: 'Semarang', url: 'https://stream.zeno.fm/8k8p44uu9feuv' },
            { id: 'dangdut4', name: 'Koplo Station', city: 'Surabaya', url: 'https://stream.zeno.fm/4g0vf8mzwhzuv' },
            { id: 'ms-tri', name: 'Ms Tri FM (Dangdut Jawa)', city: 'Semarang', url: 'https://stream.zeno.fm/mstrifm' },
            { id: 'irama-fm', name: 'Irama FM (Dangdut Klasik)', city: 'Bandung', url: 'https://stream.zeno.fm/iramafm-bdg' },
            { id: 'rhoma-station', name: 'Rhoma Irama Station', city: 'Jakarta', url: 'https://stream.zeno.fm/dangdut-klasik-id' },
          ]},
          { id: 'rock', name: 'Rock / Indie / Metal', icon: '🎸', color: '#dc2626', stations: [
            { id: 'hardrock-jkt', name: 'Hard Rock FM Jakarta', city: 'Jakarta', url: 'https://edge.iono.fm/c/533/icecast.audio' },
            { id: 'trax', name: 'Trax FM Jakarta', city: 'Jakarta', url: 'https://edge.iono.fm/c/543/icecast.audio' },
            { id: 'oz-bdg', name: 'OZ Radio Bandung', city: 'Bandung', url: 'https://stream.zeno.fm/7qhq1k7d5fzuv' },
            { id: 'ardan', name: 'Ardan Radio Bandung', city: 'Bandung', url: 'https://edge.iono.fm/c/558/icecast.audio' },
            { id: 'metal-id', name: 'Metal Radio Indonesia', city: 'Online', url: 'https://stream.zeno.fm/metal-indonesia' },
            { id: 'indie-id', name: 'Indie Radio Indonesia', city: 'Bandung', url: 'https://stream.zeno.fm/indie-id-bdg' },
          ]},
          { id: 'religi', name: 'Religi / Islami', icon: '🕌', color: '#10b981', stations: [
            { id: 'rodja', name: 'Radio Rodja 756 AM', city: 'Bogor', url: 'https://stream.rodja.com:8000/stream.mp3' },
            { id: 'dakwah', name: 'Suara Muslim Radio', city: 'Surabaya', url: 'https://stream.zeno.fm/rxy5bwgq7eeuv' },
            { id: 'hijrah-fm', name: 'Hijrah FM', city: 'Jakarta', url: 'https://stream.zeno.fm/1g4pf5e8gh8uv' },
            { id: 'alquran-rt', name: 'Radio Al-Quran RT', city: 'Jakarta', url: 'https://stream.zeno.fm/vhbpetpjtpzuv' },
            { id: 'mqfm-bdg', name: 'MQ FM Bandung (Religi)', city: 'Bandung', url: 'https://stream.zeno.fm/yw8tyaay7jzuv' },
            { id: 'global-fm-religi', name: 'Global FM (Islami)', city: 'Surabaya', url: 'https://stream.zeno.fm/globalfm-sby-religi' },
          ]},
          { id: 'campursari', name: 'Campursari / Jawa', icon: '🎎', color: '#a16207', stations: [
            { id: 'cs-solo', name: 'Radio Silaturahim (Campursari)', city: 'Solo', url: 'https://stream.zeno.fm/campursari-solo' },
            { id: 'cs-jogja', name: 'Geronimo FM Jogja (Jawa)', city: 'Yogyakarta', url: 'https://stream.zeno.fm/geronimofm-jog' },
            { id: 'retjo-buntung', name: 'Retjo Buntung FM', city: 'Yogyakarta', url: 'https://stream.zeno.fm/retjobuntung-fm' },
            { id: 'sas-fm', name: 'SAS FM Surakarta (Campursari)', city: 'Solo', url: 'https://stream.zeno.fm/sasfm-solo' },
            { id: 'gamelan-id', name: 'Gamelan Indonesia Radio', city: 'Online', url: 'https://stream.zeno.fm/gamelan-indonesia' },
            { id: 'kiai-kanjeng', name: 'Jawa Klasik (Ketoprak/Wayang)', city: 'Semarang', url: 'https://stream.zeno.fm/wayang-jawa-id' },
          ]},
          { id: 'rnb-id', name: 'R&B / Hip-Hop / Urban', icon: '🎤', color: '#8b5cf6', stations: [
            { id: 'i-radio', name: 'I-Radio Jakarta', city: 'Jakarta', url: 'https://edge.iono.fm/c/541/icecast.audio' },
            { id: 'pass-fm', name: 'Pass FM Jakarta (RnB/Urban)', city: 'Jakarta', url: 'https://stream.zeno.fm/passfm-jkt' },
            { id: 'hiphop-id', name: 'Hip-Hop Indonesia Radio', city: 'Online', url: 'https://stream.zeno.fm/hiphop-indonesia' },
            { id: 'urban-id', name: 'Urban Radio Indonesia', city: 'Jakarta', url: 'https://stream.zeno.fm/urban-radio-id' },
            { id: 'rnb-id-zeno', name: 'R&B Indonesia (Zeno)', city: 'Jakarta', url: 'https://stream.zeno.fm/rnb-id-jkt' },
            { id: 'kiss-fm-id', name: 'Kiss FM Jakarta', city: 'Jakarta', url: 'https://stream.zeno.fm/kissfm-jkt' },
          ]},
          { id: 'news', name: 'Berita / Talkshow', icon: '📰', color: '#64748b', stations: [
            { id: 'elshinta', name: 'Elshinta News & Talk', city: 'Jakarta', url: 'https://edge.iono.fm/c/538/icecast.audio' },
            { id: 'smart-fm', name: 'Smart FM Jakarta', city: 'Jakarta', url: 'https://edge.iono.fm/c/548/icecast.audio' },
            { id: 'sonora', name: 'Sonora FM (Kompas)', city: 'Jakarta', url: 'https://edge.iono.fm/c/544/icecast.audio' },
            { id: 'rri-pro3', name: 'RRI Pro 3 Jakarta', city: 'Jakarta', url: 'https://edge.iono.fm/c/3/icecast.audio' },
            { id: 'rri-pro1', name: 'RRI Pro 1 Nasional', city: 'Jakarta', url: 'https://edge.iono.fm/c/1/icecast.audio' },
            { id: 'metro-jaya', name: 'Radio Metro Jaya', city: 'Jakarta', url: 'https://stream.zeno.fm/ksbmhpb0e8zuv' },
          ]},
        ],
      },
      {
        id: 'jp', name: 'Jepang', flag: '🇯🇵', color: '#e11d48',
        genres: [
          { id: 'jpop', name: 'J-Pop / City Pop', icon: '🌸', color: '#e11d48', stations: [
            { id: 'j1-jpop', name: 'J1 Radio J-Pop', city: 'Online', url: 'https://j1.streams.radiomast.io/fm/j1jpop/stream.mp3' },
            { id: 'j1-hits', name: 'J1 Hits', city: 'Online', url: 'https://j1.streams.radiomast.io/fm/j1hits/stream.mp3' },
            { id: 'j1-oldschool', name: 'J1 Old School J-Pop', city: 'Online', url: 'https://j1.streams.radiomast.io/fm/j1oldschool/stream.mp3' },
            { id: 'j-pop-sakura', name: 'J-Pop Sakura 108', city: 'Online', url: 'https://igor.torontocast.com:1025/;' },
            { id: 'nack5', name: 'NACK5 (FM埼玉)', city: 'Saitama', url: 'https://nack5-hls-stream.nack5.co.jp/nack5/nack5.m3u8' },
            { id: 'citypop-jp', name: 'City Pop Japan Radio', city: 'Online', url: 'https://stream.laut.fm/citypop' },
          ]},
          { id: 'anime', name: 'Anime / Game OST', icon: '🎌', color: '#f43f5e', stations: [
            { id: 'anison1', name: 'Anison Radio (AnimeNfo)', city: 'Online', url: 'https://pool.anr.io/anisonfm.mp3' },
            { id: 'j1-anime', name: 'J1 Anime', city: 'Online', url: 'https://j1.streams.radiomast.io/fm/j1anime/stream.mp3' },
            { id: 'listen-anime', name: 'Listen.moe Anime', city: 'Online', url: 'https://listen.moe/stream' },
            { id: 'otakufm', name: 'OtakuFM', city: 'Online', url: 'https://stream.otakufm.de/otakufm' },
            { id: 'anison2', name: 'AniSong Radio JP', city: 'Online', url: 'https://stream.zeno.fm/anisong-jp' },
            { id: 'gameost-jp', name: 'Game OST Radio Japan', city: 'Online', url: 'https://stream.laut.fm/gameost' },
          ]},
          { id: 'lofi', name: 'Lo-Fi / Chillout', icon: '🌙', color: '#6366f1', stations: [
            { id: 'j1-lofi', name: 'J1 Lo-Fi Japan', city: 'Online', url: 'https://j1.streams.radiomast.io/fm/j1lofi/stream.mp3' },
            { id: 'nippon-lofi', name: 'Nippon Lo-Fi & Jazz', city: 'Online', url: 'https://stream.laut.fm/japanlofi' },
            { id: 'alpha-station-jp', name: 'Alpha Station FM Kyoto', city: 'Kyoto', url: 'https://stream.zeno.fm/f5l4n5bhsc8uv' },
            { id: 'sakura-lofi', name: 'Sakura Lo-Fi Beats', city: 'Online', url: 'https://stream.zeno.fm/sakuralofi128' },
            { id: 'tokyo-lofi', name: 'Tokyo Lo-Fi (Zeno)', city: 'Tokyo', url: 'https://stream.zeno.fm/tokyo-lofi-beats' },
            { id: 'kyoto-chill', name: 'Kyoto Chillout Radio', city: 'Kyoto', url: 'https://stream.zeno.fm/kyoto-chill-jp' },
          ]},
          { id: 'jrock', name: 'J-Rock / Visual Kei', icon: '🎸', color: '#7c3aed', stations: [
            { id: 'j1-jrock', name: 'J1 Rock Japan', city: 'Online', url: 'https://j1.streams.radiomast.io/fm/j1rock/stream.mp3' },
            { id: 'jrock-laut', name: 'J-Rock Radio (Laut.fm)', city: 'Online', url: 'https://stream.laut.fm/jrock' },
            { id: 'visualkei-jp', name: 'Visual Kei Radio', city: 'Online', url: 'https://stream.zeno.fm/visualkei-japan' },
            { id: 'jmetal-jp', name: 'Japanese Metal Radio', city: 'Online', url: 'https://stream.laut.fm/japanmetal' },
            { id: 'jrock2-zeno', name: 'J-Rock Station (Zeno)', city: 'Online', url: 'https://stream.zeno.fm/jrock-station-jp' },
            { id: 'punk-jp', name: 'Japanese Punk Radio', city: 'Online', url: 'https://stream.zeno.fm/jpunk-radio' },
          ]},
          { id: 'classical', name: 'Classical / Instrumental', icon: '🎻', color: '#0891b2', stations: [
            { id: 'nhk-fm-jp', name: 'NHK-FM (Classical/Culture)', city: 'Tokyo', url: 'https://nhkworldradio.nhk.or.jp/english/media/r_english_mhi128.m3u8' },
            { id: 'classical-jp-laut', name: 'Anime Instrumental (Laut.fm)', city: 'Online', url: 'https://stream.laut.fm/animeinstrumental' },
            { id: 'piano-jp', name: 'Piano Radio Japan', city: 'Online', url: 'https://stream.laut.fm/japanpiano' },
            { id: 'koto-jp', name: 'Traditional Japan Koto/Shakuhachi', city: 'Online', url: 'https://stream.laut.fm/japonaise' },
            { id: 'jazz-jp', name: 'Japanese Jazz Radio', city: 'Tokyo', url: 'https://stream.laut.fm/japanjazz' },
            { id: 'smooth-jp', name: 'Smooth Jazz Japan', city: 'Online', url: 'https://stream.zeno.fm/smooth-jazz-jp' },
          ]},
          { id: 'news', name: 'NHK / Berita', icon: '📰', color: '#64748b', stations: [
            { id: 'nhk-world', name: 'NHK World Radio Japan', city: 'Tokyo', url: 'https://nhkworldradio.nhk.or.jp/english/media/r_english_mhi128.m3u8' },
            { id: 'tbsradio-jp', name: 'TBS Radio 954 kHz', city: 'Tokyo', url: 'https://stream.zeno.fm/tbsradiotokyo' },
            { id: 'joqr-jp', name: 'Bunka Hoso (文化放送)', city: 'Tokyo', url: 'https://stream.zeno.fm/joqr1134' },
            { id: 'interfm-jp', name: 'InterFM 897', city: 'Tokyo', url: 'https://stream.zeno.fm/interfm897' },
            { id: 'nhk-r1-jp', name: 'NHK Radio 1 (日本語)', city: 'Tokyo', url: 'https://stream.zeno.fm/nhkr1japan' },
            { id: 'nhk-r2-jp', name: 'NHK Radio 2 (Education)', city: 'Tokyo', url: 'https://stream.zeno.fm/nhkr2japan' },
          ]},
        ],
      },
      {
        id: 'br', name: 'Brazil', flag: '🇧🇷', color: '#10b981',
        genres: [
          { id: 'samba', name: 'Samba / Pagode', icon: '💃', color: '#f59e0b', stations: [
            { id: 'samba-br', name: 'Rádio Samba BR (Laut.fm)', city: 'Rio de Janeiro', url: 'https://stream.laut.fm/sambabrasileiro' },
            { id: 'pagode-fm', name: 'Pagode FM', city: 'São Paulo', url: 'https://stream.zeno.fm/kfyjrzk2qbzuv' },
            { id: 'bate-ponto', name: 'Bate Ponto FM (Samba/Pagode)', city: 'Rio de Janeiro', url: 'https://stream.zeno.fm/d1p0kf2s9eruv' },
            { id: 'radio-globo-sp', name: 'Rádio Globo SP', city: 'São Paulo', url: 'https://stream.globoradio.globo.com/radio-globo-sp/mp3/256/radio-globo-sp.m3u8' },
            { id: 'sambas-enredo', name: 'Radio Sambas Enredo', city: 'Rio de Janeiro', url: 'https://stream.zeno.fm/4wd2hy7mfkzuv' },
            { id: 'batuque-br', name: 'Rádio Batuque (Samba Clássico)', city: 'Rio de Janeiro', url: 'https://stream.zeno.fm/batuque-samba-br' },
          ]},
          { id: 'axe', name: 'Axé / Forró / Baião', icon: '🎉', color: '#ef4444', stations: [
            { id: 'forro-br', name: 'Forró FM', city: 'Fortaleza', url: 'https://stream.zeno.fm/73htnbsknbzuv' },
            { id: 'axe-bahia', name: 'Rádio Bahia FM (Axé)', city: 'Salvador', url: 'https://stream.zeno.fm/4v0nyrv0zs8uv' },
            { id: 'forro-universitario', name: 'Forró Universitário', city: 'Recife', url: 'https://stream.zeno.fm/8f4fdtbxrxzuv' },
            { id: 'oxente-radio', name: 'Oxente Rádio (Forró/NE)', city: 'Nordeste', url: 'https://stream.zeno.fm/haqbnry3agzuv' },
            { id: 'carnaval-bahia', name: 'Carnaval Bahia Radio', city: 'Salvador', url: 'https://stream.zeno.fm/y3rquvf5m4zuv' },
            { id: 'bahia-fm', name: 'Bahia FM (Axé/Reggae)', city: 'Salvador', url: 'https://stream.zeno.fm/bahiafm-sva' },
          ]},
          { id: 'mpb', name: 'MPB / Bossa Nova', icon: '🎶', color: '#06b6d4', stations: [
            { id: 'bossa-nova', name: 'Bossa Nova Radio (Laut.fm)', city: 'Rio de Janeiro', url: 'https://stream.laut.fm/bossanova' },
            { id: 'mpb-hits', name: 'MPB FM Rio', city: 'Rio de Janeiro', url: 'https://stream.antradio.com.br:8000/mpbfm' },
            { id: 'eldorado-sp', name: 'Rádio Eldorado SP', city: 'São Paulo', url: 'https://stream.eldorado.com.br/eldorado' },
            { id: 'cultura-fm', name: 'Rádio Cultura FM SP', city: 'São Paulo', url: 'https://stream.zeno.fm/3fkcgmfdrfzuv' },
            { id: 'jazz-bossa', name: 'Jazz & Bossa (SomaFM)', city: 'Online', url: 'https://ice1.somafm.com/jazz-128-mp3' },
            { id: 'tropicalia', name: 'Tropicália Radio (MPB Clássica)', city: 'Rio de Janeiro', url: 'https://stream.zeno.fm/tropicalia-mpb' },
          ]},
          { id: 'funk', name: 'Funk Carioca / Hip-Hop BR', icon: '🔊', color: '#8b5cf6', stations: [
            { id: 'funk-br', name: 'Funk Brasil Radio', city: 'Rio de Janeiro', url: 'https://stream.zeno.fm/r7fjrm1zeguv' },
            { id: 'hiphop-br', name: 'Hip-Hop Brasil', city: 'São Paulo', url: 'https://stream.zeno.fm/r0ehn9fxfhzuv' },
            { id: 'funk-ostentacao', name: 'Funk Ostentação', city: 'São Paulo', url: 'https://stream.zeno.fm/mhsyb7t2mkzuv' },
            { id: 'trap-br', name: 'Trap Brasil', city: 'São Paulo', url: 'https://stream.zeno.fm/d1bswdxjt7zuv' },
            { id: 'rap-nacional', name: 'Rap Nacional Brasil', city: 'São Paulo', url: 'https://stream.zeno.fm/4n1d5mvf6bzuv' },
            { id: 'baile-funk', name: 'Baile Funk Rio (Zeno)', city: 'Rio de Janeiro', url: 'https://stream.zeno.fm/baile-funk-rio' },
          ]},
          { id: 'sertanejo', name: 'Sertanejo / Country BR', icon: '🤠', color: '#a16207', stations: [
            { id: 'sertanejo-laut', name: 'Sertanejo Radio (Laut.fm)', city: 'São Paulo', url: 'https://stream.laut.fm/sertanejo' },
            { id: 'sertanejo-zeno', name: 'Sertanejo Universitário', city: 'Goiânia', url: 'https://stream.zeno.fm/sertanejo-univ' },
            { id: 'top-fm-br', name: 'Top FM Sertanejo', city: 'Goiânia', url: 'https://stream.zeno.fm/topfm-sertanejo' },
            { id: 'caipira-br', name: 'Caipira Radio (Viola Caipira)', city: 'Minas Gerais', url: 'https://stream.zeno.fm/caipira-radio-br' },
            { id: 'country-br', name: 'Country Brasil (Linha Rural)', city: 'Goiânia', url: 'https://stream.zeno.fm/country-brasil-go' },
            { id: 'fm-do-povo', name: 'FM do Povo (Sertanejo Clás)', city: 'São Paulo', url: 'https://stream.zeno.fm/fm-do-povo-br' },
          ]},
          { id: 'news', name: 'Notícias / Talk', icon: '📰', color: '#64748b', stations: [
            { id: 'jovem-pan', name: 'Rádio Jovem Pan', city: 'São Paulo', url: 'https://cdnjp.joovip.net.br/joovip_jovempan/JovemPan.mp3' },
            { id: 'band-news', name: 'Band News FM', city: 'São Paulo', url: 'https://stream.zeno.fm/9b18h1x0xtzuv' },
            { id: 'gaucha', name: 'Rádio Gaúcha (GZH)', city: 'Porto Alegre', url: 'https://stream.gaucha.com.br/gaucha' },
            { id: 'cbn-sp', name: 'CBN São Paulo', city: 'São Paulo', url: 'https://stream.zeno.fm/5b6yq08hfhzuv' },
            { id: 'radio-nacional-br', name: 'Rádio Nacional Brasília', city: 'Brasília', url: 'https://radios.ebc.com.br/radio-nacional/icecast.audio' },
            { id: 'metropolis-br', name: 'Metrópolis FM (News Talk)', city: 'Rio de Janeiro', url: 'https://stream.zeno.fm/metropolisfm-rj' },
          ]},
        ],
      },
      {
        id: 'in', name: 'India', flag: '🇮🇳', color: '#f97316',
        genres: [
          { id: 'bollywood', name: 'Bollywood / Hindi Pop', icon: '🎵', color: '#f97316', stations: [
            { id: 'bollywood-laut', name: 'Bollywood Radio (Laut.fm)', city: 'Online', url: 'https://stream.laut.fm/bollywood' },
            { id: 'big-fm', name: 'Big FM 92.7 Delhi', city: 'Delhi', url: 'https://air.pc.cdn.bitgravity.com/air/live/pbaudio013/chunklist.m3u8' },
            { id: 'all-india-radio', name: 'All India Radio Hindi', city: 'Delhi', url: 'https://air.pc.cdn.bitgravity.com/air/live/pbaudio002/chunklist.m3u8' },
            { id: 'air-fm-gold', name: 'AIR FM Gold 106.4', city: 'Delhi', url: 'https://air.pc.cdn.bitgravity.com/air/live/pbaudio003/chunklist.m3u8' },
            { id: 'desi-bollywood', name: 'Desi Bollywood (Zeno)', city: 'Mumbai', url: 'https://stream.zeno.fm/desi-bollywood-in' },
            { id: 'retro-hits-in', name: 'Old is Gold Bollywood', city: 'Online', url: 'https://stream.laut.fm/oldgold' },
          ]},
          { id: 'classical-in', name: 'Classical / Devotional', icon: '🪗', color: '#dc2626', stations: [
            { id: 'air-classical', name: 'AIR National Classical', city: 'Delhi', url: 'https://air.pc.cdn.bitgravity.com/air/live/pbaudio001/chunklist.m3u8' },
            { id: 'bhakti-laut', name: 'Bhakti Radio (Laut.fm)', city: 'Online', url: 'https://stream.laut.fm/bhakti' },
            { id: 'carnatic-laut', name: 'Carnatic Radio (Laut.fm)', city: 'Chennai', url: 'https://stream.laut.fm/carnatic' },
            { id: 'air-carnatic', name: 'AIR Chennai (Carnatic)', city: 'Chennai', url: 'https://air.pc.cdn.bitgravity.com/air/live/pbaudio027/chunklist.m3u8' },
            { id: 'spiritual-zeno', name: 'Spiritual Radio India', city: 'Online', url: 'https://stream.zeno.fm/bqnkq97dqxzuv' },
            { id: 'hindustani-radio', name: 'Hindustani Classical (Zeno)', city: 'Varanasi', url: 'https://stream.zeno.fm/hindustani-classical' },
          ]},
          { id: 'punjabi', name: 'Punjabi / Bhangra', icon: '🥁', color: '#f59e0b', stations: [
            { id: 'punjabi-laut', name: 'Punjabi Radio (Laut.fm)', city: 'Online', url: 'https://stream.laut.fm/punjabi' },
            { id: 'bhangra-laut', name: 'Bhangra Radio (Laut.fm)', city: 'Online', url: 'https://stream.laut.fm/bhangra' },
            { id: 'air-amritsar', name: 'AIR Amritsar', city: 'Amritsar', url: 'https://air.pc.cdn.bitgravity.com/air/live/pbaudio047/chunklist.m3u8' },
            { id: 'punjabi-beats', name: 'Punjabi Beats (Zeno)', city: 'Online', url: 'https://stream.zeno.fm/v0smtd3xt7zuv' },
            { id: 'desi-radio', name: 'Desi Radio UK (Punjabi)', city: 'London', url: 'https://stream.zeno.fm/fnfgq0rdnxzuv' },
            { id: 'punjabi-virsa', name: 'Punjabi Virsa Radio', city: 'Chandigarh', url: 'https://stream.zeno.fm/punjabi-virsa' },
          ]},
          { id: 'tamil-telugu', name: 'Tamil / Telugu / South', icon: '🎶', color: '#0284c7', stations: [
            { id: 'air-chennai', name: 'AIR Chennai FM', city: 'Chennai', url: 'https://air.pc.cdn.bitgravity.com/air/live/pbaudio027/chunklist.m3u8' },
            { id: 'air-hyderabad', name: 'AIR Hyderabad FM', city: 'Hyderabad', url: 'https://air.pc.cdn.bitgravity.com/air/live/pbaudio023/chunklist.m3u8' },
            { id: 'tamil-radio', name: 'Tamil Radio (Laut.fm)', city: 'Chennai', url: 'https://stream.laut.fm/tamilradio' },
            { id: 'kollywood-zeno', name: 'Kollywood Hits (Tamil Film)', city: 'Chennai', url: 'https://stream.zeno.fm/kollywood-hits-in' },
            { id: 'telugu-radio', name: 'Telugu Radio (Zeno)', city: 'Hyderabad', url: 'https://stream.zeno.fm/telugu-radio-hyd' },
            { id: 'rayudu-fm', name: 'Rayudu FM (Telugu Folk)', city: 'Hyderabad', url: 'https://stream.zeno.fm/rayudu-fm-telugu' },
          ]},
          { id: 'electronic-in', name: 'Electronic / Indie IN', icon: '🎧', color: '#8b5cf6', stations: [
            { id: 'indie-in', name: 'Indie Radio India (Zeno)', city: 'Mumbai', url: 'https://stream.zeno.fm/3u6hhtfhfpzuv' },
            { id: 'chill-goa', name: 'Psy Trance / Goa Chill', city: 'Goa', url: 'https://stream.laut.fm/goatrance' },
            { id: 'lounge-in', name: 'India Lounge (Zeno)', city: 'Mumbai', url: 'https://stream.zeno.fm/indialounge128' },
            { id: 'electroindian', name: 'Electronic India (Zeno)', city: 'Online', url: 'https://stream.zeno.fm/azhbv0eafdzuv' },
            { id: 'fusion-in', name: 'Fusion Radio India', city: 'Bangalore', url: 'https://stream.zeno.fm/t9gvqp4kzuzuv' },
            { id: 'goa-trance', name: 'Goa Trance Classics', city: 'Goa', url: 'https://stream.laut.fm/goatrance' },
          ]},
          { id: 'news-in', name: 'News / Talk IN', icon: '📰', color: '#64748b', stations: [
            { id: 'bbc-hindi', name: 'BBC Hindi Service', city: 'London', url: 'https://stream.live.vc.bbcmedia.co.uk/bbc_hindi_news' },
            { id: 'air-news', name: 'All India Radio News', city: 'Delhi', url: 'https://air.pc.cdn.bitgravity.com/air/live/pbaudio002/chunklist.m3u8' },
            { id: 'voa-hindi', name: 'VOA Hindi', city: 'Washington', url: 'https://voa-instreams.akamaized.net/voa/mp3/urdu' },
            { id: 'dw-hindi', name: 'DW Hindi', city: 'Bonn', url: 'https://stream.laut.fm/dwhindi' },
            { id: 'air-fm-rainbow', name: 'AIR FM Rainbow (English)', city: 'Mumbai', url: 'https://air.pc.cdn.bitgravity.com/air/live/pbaudio003/chunklist.m3u8' },
            { id: 'radio-india-news', name: 'Radio India News (Zeno)', city: 'Delhi', url: 'https://stream.zeno.fm/news-india-radio' },
          ]},
        ],
      },
      {
        id: 'mx', name: 'Meksiko', flag: '🇲🇽', color: '#10b981',
        genres: [
          { id: 'pop-mx', name: 'Pop / Reggaeton', icon: '🎵', color: '#10b981', stations: [
            { id: 'exa-fm', name: 'Exa FM 104.9', city: 'México DF', url: 'https://stream.exafm.com/exa-128.mp3' },
            { id: 'ke-buena', name: 'Ke Buena 92.9', city: 'México DF', url: 'https://stream.radioformula.com.mx/kebuena-128.mp3' },
            { id: 'hit-mx', name: 'Hit FM México', city: 'México DF', url: 'https://stream.zeno.fm/5t2g7ywybazuv' },
            { id: 'beats-mx', name: 'Beats Radio MX (Urban)', city: 'México DF', url: 'https://stream.zeno.fm/yxhe8bmt3uzuv' },
            { id: 'reaktor-pop', name: 'Pop & Reggaeton MX (Zeno)', city: 'Guadalajara', url: 'https://stream.zeno.fm/pop-reggaeton-mx' },
            { id: 'estereo-cien', name: 'Estéreo Cien 99.7', city: 'México DF', url: 'https://stream.zeno.fm/estereo-cien-mx' },
          ]},
          { id: 'ranchera', name: 'Ranchera / Mariachi', icon: '🪗', color: '#f59e0b', stations: [
            { id: 'rancheras-laut', name: 'Rancheras (Laut.fm)', city: 'Online', url: 'https://stream.laut.fm/rancheras' },
            { id: 'mariachi-zeno', name: 'Mariachi Radio', city: 'Jalisco', url: 'https://stream.zeno.fm/0q6wdh70e3zuv' },
            { id: 'la-mejor', name: 'La Mejor 97.9 FM', city: 'México DF', url: 'https://stream.zeno.fm/thzqy5v12m8uv' },
            { id: 'el-rey-radio', name: 'El Rey Radio', city: 'México DF', url: 'https://stream.zeno.fm/tpjpqs1y3pzuv' },
            { id: 'w-radio-mx', name: 'W Radio México', city: 'México DF', url: 'https://stream.w-radio.com.mx/w-radio-128.mp3' },
            { id: 'la-z-mx', name: 'La Z Ranchera (Laut.fm)', city: 'Jalisco', url: 'https://stream.laut.fm/lazranchera' },
          ]},
          { id: 'norteno', name: 'Norteño / Banda / Grupero', icon: '🎺', color: '#dc2626', stations: [
            { id: 'norteno-laut', name: 'Norteño Radio (Laut.fm)', city: 'Online', url: 'https://stream.laut.fm/norteno' },
            { id: 'grupero-mx', name: 'Grupero Radio MX', city: 'Monterrey', url: 'https://stream.zeno.fm/n7fqebj49xzuv' },
            { id: 'banda-mx', name: 'Banda FM México', city: 'Guadalajara', url: 'https://stream.zeno.fm/fyb14mpfeszuv' },
            { id: 'que-buena', name: 'Que Buena 93.9', city: 'México DF', url: 'https://stream.zeno.fm/4ykm2zybhszuv' },
            { id: 'rcm-norteno', name: 'RCM Norteño', city: 'Monterrey', url: 'https://stream.zeno.fm/1xv5eycobyzuv' },
            { id: 'corridos-mx', name: 'Corridos Radio México', city: 'Sinaloa', url: 'https://stream.zeno.fm/corridos-radio-mx' },
          ]},
          { id: 'electronic-mx', name: 'Electronic / Dance MX', icon: '🎧', color: '#8b5cf6', stations: [
            { id: 'reactor-mx', name: 'Reactor 105.7 FM', city: 'México DF', url: 'https://stream.zeno.fm/reactor1057mx' },
            { id: 'ibero-mx', name: 'Ibero 90.9 FM (Indie/Alt)', city: 'México DF', url: 'https://stream.zeno.fm/ibero909fmmx' },
            { id: 'wfm-mx', name: 'WFM 96.9 FM (Electronic)', city: 'México DF', url: 'https://stream.zeno.fm/wfm969mx' },
            { id: 'ritmo-mx', name: 'Ritmo 92.9 (Dance/House)', city: 'Guadalajara', url: 'https://stream.zeno.fm/ritmo929mx' },
            { id: 'hitz-mx', name: 'Hitz FM México (EDM)', city: 'Online', url: 'https://stream.zeno.fm/hitzfmmx' },
            { id: 'rave-mx', name: 'Rave Radio México (Techno)', city: 'México DF', url: 'https://stream.zeno.fm/rave-radio-mx' },
          ]},
          { id: 'latin', name: 'Salsa / Latin Jazz / Cumbia', icon: '🎶', color: '#06b6d4', stations: [
            { id: 'salsa-mx', name: 'Salsa Radio México (Laut.fm)', city: 'Online', url: 'https://stream.laut.fm/salsa' },
            { id: 'cumbia-mx', name: 'Cumbia Radio MX', city: 'México DF', url: 'https://stream.zeno.fm/cumbia-mexico' },
            { id: 'tropical-mx', name: 'Radio Tropical México', city: 'Veracruz', url: 'https://stream.zeno.fm/tropical-mx-ver' },
            { id: 'latin-jazz-mx', name: 'Latin Jazz Radio (Laut.fm)', city: 'Online', url: 'https://stream.laut.fm/latinjazz' },
            { id: 'merengue-mx', name: 'Merengue & Bachata MX', city: 'Online', url: 'https://stream.laut.fm/merengue' },
            { id: 'salsa-clasica', name: 'Salsa Clásica Radio', city: 'Online', url: 'https://stream.zeno.fm/salsa-clasica-la' },
          ]},
          { id: 'news-mx', name: 'Noticias / Info MX', icon: '📰', color: '#64748b', stations: [
            { id: 'w-radio-news', name: 'W Radio Noticias', city: 'México DF', url: 'https://stream.w-radio.com.mx/w-radio-128.mp3' },
            { id: 'radio-formula', name: 'Radio Fórmula', city: 'México DF', url: 'https://stream.radioformula.com.mx/formula-128.mp3' },
            { id: 'noticias-mx', name: 'Noticias MVS Radio', city: 'México DF', url: 'https://stream.zeno.fm/oj8tpbwfbhzuv' },
            { id: 'radio-red-mx', name: 'Radio Red 88.1 FM', city: 'México DF', url: 'https://stream.zeno.fm/radiored881mx' },
            { id: 'imagen-radio-mx', name: 'Imagen Radio 90.5', city: 'México DF', url: 'https://stream.zeno.fm/imagen905mx' },
            { id: 'bbc-mundo-mx', name: 'BBC Mundo en Español', city: 'London', url: 'https://stream.live.vc.bbcmedia.co.uk/bbc_mundo_news' },
          ]},
        ],
      },
      {
        id: 'kr', name: 'Korea Selatan', flag: '🇰🇷', color: '#06b6d4',
        genres: [
          { id: 'kpop', name: 'K-Pop / K-R&B', icon: '💫', color: '#06b6d4', stations: [
            { id: 'kpop1', name: 'K-Pop Radio (Laut.fm)', city: 'Online', url: 'https://stream.laut.fm/kpop' },
            { id: 'kpop-hits', name: 'K-Pop Hits Radio (Zeno)', city: 'Online', url: 'https://stream.zeno.fm/gbkda1r5czzuv' },
            { id: 'kbs-cool', name: 'KBS Cool FM (공식)', city: 'Seoul', url: 'https://serpent.kbs.co.kr/mediaproxy/manifest/coolFM/hls/live.m3u8' },
            { id: 'allkpop-radio', name: 'All Kpop Radio', city: 'Online', url: 'https://stream.zeno.fm/ql0hf0meyezuv' },
            { id: 'kpop-mix', name: 'K-Pop Mix Station', city: 'Online', url: 'https://stream.zeno.fm/kpop-mix-station' },
            { id: 'kpop-2nd-gen', name: 'K-Pop 2nd Gen (Zeno)', city: 'Online', url: 'https://stream.zeno.fm/kpop-2nd-gen' },
          ]},
          { id: 'krnb', name: 'K-R&B / Hip-Hop', icon: '🎤', color: '#8b5cf6', stations: [
            { id: 'kr-hiphop', name: 'Korean Hip-Hop (Laut.fm)', city: 'Online', url: 'https://stream.laut.fm/khiphop' },
            { id: 'kr-rnb', name: 'K-R&B Station (Zeno)', city: 'Online', url: 'https://stream.zeno.fm/fgb7t4o2cxzuv' },
            { id: 'idol-radio', name: 'Idol Radio MBC', city: 'Seoul', url: 'https://stream.zeno.fm/pjrdq4nbnmzuv' },
            { id: 'kr-urban', name: 'Korean Urban Radio (Laut.fm)', city: 'Seoul', url: 'https://stream.laut.fm/koreanurban' },
            { id: 'zion-kr', name: 'Zion T Style KRnB', city: 'Seoul', url: 'https://stream.zeno.fm/kr-rnb-smooth' },
            { id: 'kr-trap', name: 'Korean Trap & Hip-Hop', city: 'Seoul', url: 'https://stream.zeno.fm/kr-trap-hiphop' },
          ]},
          { id: 'k-indie', name: 'K-Indie / Alternative', icon: '🎸', color: '#f43f5e', stations: [
            { id: 'k-indie1', name: 'K-Indie Radio (Zeno)', city: 'Seoul', url: 'https://stream.zeno.fm/0r8ydry8cuzuv' },
            { id: 'ebs-radio', name: 'EBS FM (공식)', city: 'Seoul', url: 'https://ebsm3u8.out.myebs.co.kr:8443/streams/ebsfm/ebsfm.m3u8' },
            { id: 'k-rock-zeno', name: 'K-Rock Station (Zeno)', city: 'Busan', url: 'https://stream.zeno.fm/dg08t7n9h0zuv' },
            { id: 'indie-seoul', name: 'Indie Seoul Pop', city: 'Seoul', url: 'https://stream.zeno.fm/wf0bnzd0gjzuv' },
            { id: 'k-shoegaze', name: 'Korean Shoegaze/Indie', city: 'Seoul', url: 'https://stream.zeno.fm/k-shoegaze' },
            { id: 'garage-kr', name: 'Korean Garage Rock (Laut.fm)', city: 'Busan', url: 'https://stream.laut.fm/koreanrock' },
          ]},
          { id: 'trot', name: 'Trot / 트로트', icon: '🎶', color: '#f97316', stations: [
            { id: 'trot-kr', name: 'Trot Radio Korea (Zeno)', city: 'Seoul', url: 'https://stream.zeno.fm/trot-korea' },
            { id: 'trot-laut', name: 'Korean Trot (Laut.fm)', city: 'Online', url: 'https://stream.laut.fm/trot' },
            { id: 'trot-classic', name: 'Trot Classic Station', city: 'Seoul', url: 'https://stream.zeno.fm/trot-classic-kr' },
            { id: 'mr-trot', name: 'Mr. Trot Radio', city: 'Seoul', url: 'https://stream.zeno.fm/mr-trot-kr' },
            { id: 'trot-fm', name: 'Trot FM 24', city: 'Seoul', url: 'https://stream.zeno.fm/trotfm24-kr' },
            { id: 'kbs-2fm', name: 'KBS 2FM (Trot/Pop)', city: 'Seoul', url: 'https://serpent.kbs.co.kr/mediaproxy/manifest/2FM/hls/live.m3u8' },
          ]},
          { id: 'kr-lofi', name: 'Lo-Fi / Chillout KR', icon: '🌙', color: '#6366f1', stations: [
            { id: 'kr-lofi1', name: 'Korean Lofi (Zeno)', city: 'Online', url: 'https://stream.zeno.fm/baq0u5e8nzzuv' },
            { id: 'seoul-chill', name: 'Seoul Chill Beats', city: 'Seoul', url: 'https://stream.zeno.fm/6v2rqbpey7zuv' },
            { id: 'k-jazz', name: 'K-Jazz Radio (Laut.fm)', city: 'Seoul', url: 'https://stream.laut.fm/kjazz' },
            { id: 'han-river', name: 'Han River Lo-Fi', city: 'Seoul', url: 'https://stream.zeno.fm/han-river-lofi' },
            { id: 'study-kr', name: 'Study With Me Korea', city: 'Seoul', url: 'https://stream.zeno.fm/study-kr-beats' },
            { id: 'chill-cafe-kr', name: 'Chill Café Korea', city: 'Seoul', url: 'https://stream.zeno.fm/chill-cafe-kr' },
          ]},
          { id: 'news-kr', name: 'News / Talk KR', icon: '📰', color: '#64748b', stations: [
            { id: 'kbs-world-news', name: 'KBS World Radio', city: 'Seoul', url: 'https://serpent.kbs.co.kr/mediaproxy/manifest/world/hls/live.m3u8' },
            { id: 'ytn-radio', name: 'YTN Radio', city: 'Seoul', url: 'https://stream.zeno.fm/aqr4rp4x3rzuv' },
            { id: 'mbc-news-kr', name: 'MBC Standard FM', city: 'Seoul', url: 'https://stream.zeno.fm/3b06nj0d84zuv' },
            { id: 'tbs-efm', name: 'TBS eFM 101.3 (영어뉴스)', city: 'Seoul', url: 'https://stream.zeno.fm/tbsefm1013' },
            { id: 'arirang-kr', name: 'Arirang Radio (영어 방송)', city: 'Seoul', url: 'https://stream.zeno.fm/arirang-radio-kr' },
            { id: 'sbs-love-fm', name: 'SBS Love FM', city: 'Seoul', url: 'https://stream.zeno.fm/sbs-love-fm-kr' },
          ]},
        ],
      }
    ],
  },
];

